### ISSUE TITLE
Incompatibility with RSpec

### ISSUE THREAD

**Issue by joeldrapper** [camertron/onload#1]
I’m running into an incompatibility with RSpec on the latest version from RubyGems and the latest `main`.

### Steps to reproduce

1. Add `onload` to Gemfile
2. Run `bundle install`
3. Run `bundle exec rspec`

### Output

```
bundler: failed to load command: rspec (/Users/joeldrapper/.rbenv/versions/3.2.2/bin/rspec)
/Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/formatters/progress_formatter.rb:8:in `<module:Formatters>': uninitialized constant RSpec::Core::Formatters::ProgressFormatter (NameError)
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/formatters/progress_formatter.rb:6:in `<module:Core>'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/formatters/progress_formatter.rb:5:in `<module:RSpec>'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/formatters/progress_formatter.rb:4:in `<main>'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/onload-1.0.0/lib/onload/core_ext/kernel_zeitwerk.rb:25:in `load'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/onload-1.0.0/lib/onload/core_ext/kernel_zeitwerk.rb:25:in `load'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/onload-1.0.0/lib/onload/core_ext/kernel_zeitwerk.rb:56:in `require'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/formatters.rb:218:in `built_in_formatter'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/formatters.rb:182:in `find_formatter'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/formatters.rb:152:in `add'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/formatters.rb:127:in `setup_default'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/reporter.rb:47:in `block in prepare_default'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/reporter.rb:236:in `ensure_listeners_ready'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/reporter.rb:207:in `notify'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/reporter.rb:100:in `message'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/world.rb:206:in `report_filter_message'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/world.rb:197:in `announce_filters'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:104:in `ensure in setup'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:104:in `setup'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:86:in `run'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:71:in `run'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:45:in `invoke'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/exe/rspec:4:in `<top (required)>'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/bin/rspec:25:in `load'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/bin/rspec:25:in `<top (required)>'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:58:in `load'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:23:in `run'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli.rb:492:in `exec'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli.rb:34:in `dispatch'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli.rb:28:in `start'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/exe/bundle:45:in `block in <top (required)>'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/exe/bundle:33:in `<top (required)>'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/bin/bundle:25:in `load'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/bin/bundle:25:in `<main>'
/Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/did_you_mean.rb:5:in `<module:Core>': uninitialized constant RSpec::Core::DidYouMean (NameError)
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/did_you_mean.rb:2:in `<module:RSpec>'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/did_you_mean.rb:1:in `<main>'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/onload-1.0.0/lib/onload/core_ext/kernel_zeitwerk.rb:25:in `load'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/onload-1.0.0/lib/onload/core_ext/kernel_zeitwerk.rb:25:in `load'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/onload-1.0.0/lib/onload/core_ext/kernel_zeitwerk.rb:56:in `require'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/configuration.rb:2120:in `rescue in load_file_handling_errors'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/configuration.rb:2116:in `load_file_handling_errors'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/configuration.rb:1576:in `block in requires='
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/configuration.rb:1576:in `each'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/configuration.rb:1576:in `requires='
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/configuration_options.rb:113:in `block in process_options_into'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/configuration_options.rb:112:in `each'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/configuration_options.rb:112:in `process_options_into'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/configuration_options.rb:22:in `configure'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:132:in `configure'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:99:in `setup'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:86:in `run'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:71:in `run'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:45:in `invoke'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/exe/rspec:4:in `<top (required)>'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/bin/rspec:25:in `load'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/bin/rspec:25:in `<top (required)>'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:58:in `load'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:23:in `run'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli.rb:492:in `exec'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli.rb:34:in `dispatch'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli.rb:28:in `start'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/exe/bundle:45:in `block in <top (required)>'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/exe/bundle:33:in `<top (required)>'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/bin/bundle:25:in `load'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/bin/bundle:25:in `<main>'
/Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/onload-1.0.0/lib/onload/core_ext/kernel_zeitwerk.rb:25:in `load': cannot load such file -- /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.8/lib/zeitwerk (LoadError)
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/onload-1.0.0/lib/onload/core_ext/kernel_zeitwerk.rb:25:in `load'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/onload-1.0.0/lib/onload/core_ext/kernel_zeitwerk.rb:56:in `require'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/onload-1.0.0/lib/onload/ext/zeitwerk/loader.rb:3:in `<main>'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/onload-1.0.0/lib/onload/core_ext/kernel_zeitwerk.rb:25:in `load'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/onload-1.0.0/lib/onload/core_ext/kernel_zeitwerk.rb:25:in `load'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/onload-1.0.0/lib/onload/core_ext/kernel_zeitwerk.rb:56:in `require'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/onload-1.0.0/lib/onload.rb:20:in `install!'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/onload-1.0.0/lib/onload/railtie.rb:8:in `block in <class:Railtie>'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/initializable.rb:32:in `instance_exec'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/initializable.rb:32:in `run'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:228:in `block in tsort_each'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/initializable.rb:50:in `each'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/initializable.rb:50:in `tsort_each_child'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:415:in `call'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:415:in `each_strongly_connected_component_from'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/initializable.rb:50:in `each'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/initializable.rb:50:in `tsort_each_child'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:415:in `call'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:415:in `each_strongly_connected_component_from'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/initializable.rb:50:in `each'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/initializable.rb:50:in `tsort_each_child'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:415:in `call'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:415:in `each_strongly_connected_component_from'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:347:in `each'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:347:in `call'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:226:in `tsort_each'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:205:in `tsort_each'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/initializable.rb:60:in `run_initializers'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/application.rb:372:in `initialize!'
	from /Users/joeldrapper/src/clearscope/config/environment.rb:7:in `<top (required)>'
	from /Users/joeldrapper/src/clearscope/spec/rails_helper.rb:6:in `require_relative'
	from /Users/joeldrapper/src/clearscope/spec/rails_helper.rb:6:in `<top (required)>'
	from <internal:/Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/configuration.rb:2117:in `load_file_handling_errors'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/configuration.rb:1576:in `block in requires='
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/configuration.rb:1576:in `each'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/configuration.rb:1576:in `requires='
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/configuration_options.rb:113:in `block in process_options_into'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/configuration_options.rb:112:in `each'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/configuration_options.rb:112:in `process_options_into'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/configuration_options.rb:22:in `configure'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:132:in `configure'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:99:in `setup'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:86:in `run'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:71:in `run'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:45:in `invoke'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/exe/rspec:4:in `<top (required)>'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/bin/rspec:25:in `load'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/bin/rspec:25:in `<top (required)>'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:58:in `load'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:23:in `run'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli.rb:492:in `exec'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli.rb:34:in `dispatch'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/cli.rb:28:in `start'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/exe/bundle:45:in `block in <top (required)>'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.12/exe/bundle:33:in `<top (required)>'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/bin/bundle:25:in `load'
	from /Users/joeldrapper/.rbenv/versions/3.2.2/bin/bundle:25:in `<main>'
```

**Comment by camertron** [comment]
Hey @joeldrapper thanks for filing this. I just tried to reproduce it and found/fixed a bug affecting C extensions. After fixing it, everything works as expected, i.e. I'm not getting the same stack trace you posted. Any chance you can put up a test repo?

**Comment by joeldrapper** [comment]
Awesome! Sure, feel free to assign it to me, and I’ll see what I can do.
